baseURL = "http://hotch.money/"
languageCode = "en-us"
title = "Sam Hotchkiss"
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Sam Hotchkiss"
    info = "RPG Designer and Software Developer"
    description = "Sam Hotchkiss's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    #footercontent = "Enter a text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 1
    url = "mailto:hotch@pm.me"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/Hotchmoney/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 3
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/sam-hotchkiss/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Games"
    weight = 2
    url  = "https://hotchk.itch.io/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "http://knowledgecheck.tumblr.com/"
[[menu.main]]
    name = "PGP"
    weight = 4
    url  = "http://pgp.mit.edu/pks/lookup?op=get&search=0x50270CB2B48B485E"